# Generated by Django 5.2.17 on 2026-09-25 16:39

import django.core.validators
import django.db.models.deletion
import viajes.validadores
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=80, unique=True, verbose_name="nombre"),
                ),
                (
                    "codigo_iso",
                    models.CharField(
                        help_text="Código ISO 3166-1 de 2 letras, por ejemplo: CL, FR, JP.",
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$",
                                "Usa 2 letras mayúsculas, por ejemplo: CL.",
                            )
                        ],
                        verbose_name="código ISO",
                    ),
                ),
                (
                    "continente",
                    models.CharField(
                        choices=[
                            ("africa", "África"),
                            ("america_norte", "América del Norte"),
                            ("america_central", "Centroamérica y el Caribe"),
                            ("america_sur", "América del Sur"),
                            ("asia", "Asia"),
                            ("europa", "Europa"),
                            ("oceania", "Oceanía"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="continente",
                    ),
                ),
            ],
            options={
                "verbose_name": "país",
                "verbose_name_plural": "países",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Viaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        help_text="Ciudad o región, por ejemplo: París, Bali, Cartagena.",
                        max_length=100,
                        validators=[viajes.validadores.ValidadorTextoConLetras()],
                        verbose_name="destino",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Opcional si el viaje aún no termina o todavía no la conoces.",
                        null=True,
                        verbose_name="fecha de regreso",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("completado", "Completado"),
                            ("en_progreso", "En progreso"),
                            ("planificado", "Planificado"),
                        ],
                        default="planificado",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Lo que pasó, recuerdos, recomendaciones…",
                        max_length=5000,
                        verbose_name="notas",
                    ),
                ),
                (
                    "favorito",
                    models.BooleanField(default=False, verbose_name="favorito"),
                ),
                (
                    "calificacion",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (5, "★★★★★ Inolvidable"),
                            (4, "★★★★☆ Muy bueno"),
                            (3, "★★★☆☆ Bueno"),
                            (2, "★★☆☆☆ Regular"),
                            (1, "★☆☆☆☆ Malo"),
                        ],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="calificación",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "actualizado",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "compartido_con",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Personas que pueden ver este viaje (solo lectura).",
                        related_name="viajes_compartidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compartido con",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viajes",
                        to="viajes.pais",
                        verbose_name="país",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="viajero",
                    ),
                ),
            ],
            options={
                "verbose_name": "viaje",
                "verbose_name_plural": "viajes",
                "ordering": ["-fecha_inicio", "-creado"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-fecha_inicio"],
                        name="viaje_usuario_fecha_idx",
                    ),
                    models.Index(
                        fields=["usuario", "estado"], name="viaje_usuario_estado_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fecha_fin__isnull", True),
                            ("fecha_fin__gte", models.F("fecha_inicio")),
                            _connector="OR",
                        ),
                        name="viaje_regreso_posterior_inicio",
                        violation_error_message="La fecha de regreso no puede ser anterior a la de inicio.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("calificacion__isnull", True),
                            models.Q(
                                ("calificacion__gte", 1), ("calificacion__lte", 5)
                            ),
                            _connector="OR",
                        ),
                        name="viaje_calificacion_1_a_5",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "en_progreso")),
                        fields=("usuario",),
                        name="viaje_un_solo_viaje_en_progreso",
                        violation_error_message="Solo puedes tener un viaje en progreso a la vez.",
                    ),
                ],
            },
        ),
    ]
