# Generated by Django 5.2.17 on 2026-09-28 01:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import viajes.models
import viajes.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_cargar_paises'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='presupuesto',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. En pesos chilenos, sin puntos: por ejemplo 850000.', null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='presupuesto'),
        ),
        migrations.CreateModel(
            name='FotoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=200, upload_to=viajes.models.ruta_foto, verbose_name='foto')),
                ('subida', models.DateTimeField(auto_now_add=True, verbose_name='subida')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='viajes.viaje', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'foto de viaje',
                'verbose_name_plural': 'fotos de viaje',
                'ordering': ['subida'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Vuelo Santiago–Lima.', max_length=120, validators=[viajes.validadores.ValidadorTextoConLetras()], verbose_name='descripción')),
                ('categoria', models.CharField(choices=[('transporte', '🚌 Transporte'), ('alojamiento', '🏨 Alojamiento'), ('comida', '🍽️ Comida'), ('actividades', '🎟️ Actividades'), ('compras', '🛍️ Compras'), ('otros', '📦 Otros')], default='otros', max_length=12, verbose_name='categoría')),
                ('monto', models.PositiveIntegerField(help_text='En pesos chilenos.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='monto')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viajes.viaje', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-fecha', '-creado'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='gasto_monto_positivo')],
            },
        ),
    ]
