# Generated by Django 5.2.17 on 2026-09-28 19:37

import django.db.models.deletion
import viajes.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viajes", "0003_presupuesto_gastos_fotos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="día")),
                (
                    "hora",
                    models.TimeField(
                        blank=True,
                        help_text="Opcional.",
                        null=True,
                        verbose_name="hora",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej: Tour por el centro histórico.",
                        max_length=120,
                        validators=[viajes.validadores.ValidadorTextoConLetras()],
                        verbose_name="actividad",
                    ),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True,
                        help_text="Opcional. Ej: Plaza de Armas.",
                        max_length=120,
                        verbose_name="lugar",
                    ),
                ),
                (
                    "realizada",
                    models.BooleanField(default=False, verbose_name="realizada"),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "viaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="viajes.viaje",
                        verbose_name="viaje",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad",
                "verbose_name_plural": "actividades",
                "ordering": [
                    "fecha",
                    models.OrderBy(models.F("hora"), nulls_last=True),
                    "creado",
                ],
                "indexes": [
                    models.Index(
                        fields=["viaje", "fecha"], name="actividad_viaje_fecha_idx"
                    )
                ],
            },
        ),
    ]
