# Generated by Django 5.2.17 on 2026-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_moneda_de_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoviaje',
            name='credito',
            field=models.CharField(blank=True, help_text='Autor y licencia, si la foto no es propia.', max_length=200, verbose_name='crédito'),
        ),
    ]
