# Generated by Django 5.2.17 on 2026-09-30 13:51

import django.db.models.deletion
import viajes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_credito_de_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=viajes.models.generar_token, editable=False, max_length=64, unique=True, verbose_name='código')),
                ('telefono', models.CharField(help_text='A quién se le envió, en formato +56912345678.', max_length=20, verbose_name='teléfono')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('vence', models.DateTimeField(verbose_name='vence')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_fotos', to='viajes.viaje', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'enlace a las fotos',
                'verbose_name_plural': 'enlaces a las fotos',
                'ordering': ['-creado'],
            },
        ),
    ]
