# Generated by Django 5.2.17 on 2026-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_enlaces_a_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacefotos',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre de quien recibe el enlace.', max_length=60, verbose_name='contacto'),
        ),
    ]
