# Generated by Django 5.2.17 on 2026-09-30 18:20

import django.db.models.deletion
import viajes.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0008_contacto_del_enlace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, validators=[viajes.validadores.ValidadorTextoConLetras()], verbose_name='nombre')),
                ('relacion', models.CharField(choices=[('pareja', 'Pareja'), ('familia', 'Familia'), ('amistad', 'Amistad'), ('trabajo', 'Trabajo'), ('otra', 'Otra')], default='amistad', max_length=10, verbose_name='relación')),
                ('email', models.EmailField(blank=True, help_text='Opcional. Solo lo ves tú.', max_length=254, verbose_name='correo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanantes', to='viajes.viaje', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'acompañante',
                'verbose_name_plural': 'acompañantes',
                'ordering': ['creado'],
            },
        ),
    ]
