# Generated by Django 5.2.17 on 2026-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_acompanantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='publico',
            field=models.BooleanField(default=False, help_text='Otras personas con cuenta en el sitio pueden verlo en «Viajes públicos» (solo lectura).', verbose_name='público'),
        ),
    ]
