# Generated by Django 5.2.17 on 2026-09-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
    ]
