# Generated by Django 4.2.30 on 2026-08-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('duracion_dias', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('completado', 'Completado ✓'), ('en_progreso', 'En progreso 🔄'), ('planificado', 'Planificado 📋')], default='planificado', max_length=20)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
