"""
Monedas extranjeras para registrar en qué moneda se pagó un gasto.

Los gastos siempre se guardan en pesos chilenos (así se comparan con el presupuesto);
la moneda extranjera es un registro adicional de lo que se pagó allá.
Códigos ISO 4217.
"""

import unicodedata

# código: (nombre en singular, nombre en plural)
MONEDAS = {
    "AED": ("dírham emiratí", "dírhams emiratíes"),
    "AFN": ("afgani", "afganis"),
    "ALL": ("lek albanés", "leks albaneses"),
    "AMD": ("dram armenio", "drams armenios"),
    "AOA": ("kwanza angoleño", "kwanzas angoleños"),
    "ARS": ("peso argentino", "pesos argentinos"),
    "AUD": ("dólar australiano", "dólares australianos"),
    "AWG": ("florín arubeño", "florines arubeños"),
    "AZN": ("manat azerbaiyano", "manats azerbaiyanos"),
    "BAM": ("marco bosnio", "marcos bosnios"),
    "BBD": ("dólar de Barbados", "dólares de Barbados"),
    "BDT": ("taka bangladesí", "takas bangladesíes"),
    "BHD": ("dinar bareiní", "dinares bareiníes"),
    "BIF": ("franco burundés", "francos burundeses"),
    "BND": ("dólar de Brunéi", "dólares de Brunéi"),
    "BOB": ("boliviano", "bolivianos"),
    "BRL": ("real brasileño", "reales brasileños"),
    "BSD": ("dólar bahameño", "dólares bahameños"),
    "BTN": ("ngultrum butanés", "ngultrums butaneses"),
    "BWP": ("pula de Botsuana", "pulas de Botsuana"),
    "BYN": ("rublo bielorruso", "rublos bielorrusos"),
    "BZD": ("dólar beliceño", "dólares beliceños"),
    "CAD": ("dólar canadiense", "dólares canadienses"),
    "CDF": ("franco congoleño", "francos congoleños"),
    "CHF": ("franco suizo", "francos suizos"),
    "CNY": ("yuan chino", "yuanes chinos"),
    "COP": ("peso colombiano", "pesos colombianos"),
    "CRC": ("colón costarricense", "colones costarricenses"),
    "CUP": ("peso cubano", "pesos cubanos"),
    "CVE": ("escudo caboverdiano", "escudos caboverdianos"),
    "CZK": ("corona checa", "coronas checas"),
    "DJF": ("franco yibutiano", "francos yibutianos"),
    "DKK": ("corona danesa", "coronas danesas"),
    "DOP": ("peso dominicano", "pesos dominicanos"),
    "DZD": ("dinar argelino", "dinares argelinos"),
    "EGP": ("libra egipcia", "libras egipcias"),
    "ERN": ("nakfa eritreo", "nakfas eritreos"),
    "ETB": ("birr etíope", "birrs etíopes"),
    "EUR": ("euro", "euros"),
    "FJD": ("dólar fiyiano", "dólares fiyianos"),
    "GBP": ("libra esterlina", "libras esterlinas"),
    "GEL": ("lari georgiano", "laris georgianos"),
    "GHS": ("cedi ghanés", "cedis ghaneses"),
    "GMD": ("dalasi gambiano", "dalasis gambianos"),
    "GNF": ("franco guineano", "francos guineanos"),
    "GTQ": ("quetzal", "quetzales"),
    "GYD": ("dólar guyanés", "dólares guyaneses"),
    "HKD": ("dólar de Hong Kong", "dólares de Hong Kong"),
    "HNL": ("lempira", "lempiras"),
    "HTG": ("gourde haitiano", "gourdes haitianos"),
    "HUF": ("forinto húngaro", "forintos húngaros"),
    "IDR": ("rupia indonesia", "rupias indonesias"),
    "ILS": ("séquel israelí", "séqueles israelíes"),
    "INR": ("rupia india", "rupias indias"),
    "IQD": ("dinar iraquí", "dinares iraquíes"),
    "IRR": ("rial iraní", "riales iraníes"),
    "ISK": ("corona islandesa", "coronas islandesas"),
    "JMD": ("dólar jamaiquino", "dólares jamaiquinos"),
    "JOD": ("dinar jordano", "dinares jordanos"),
    "JPY": ("yen japonés", "yenes japoneses"),
    "KES": ("chelín keniano", "chelines kenianos"),
    "KGS": ("som kirguís", "soms kirguises"),
    "KHR": ("riel camboyano", "rieles camboyanos"),
    "KMF": ("franco comorense", "francos comorenses"),
    "KPW": ("won norcoreano", "wones norcoreanos"),
    "KRW": ("won surcoreano", "wones surcoreanos"),
    "KWD": ("dinar kuwaití", "dinares kuwaitíes"),
    "KZT": ("tenge kazajo", "tenges kazajos"),
    "LAK": ("kip laosiano", "kips laosianos"),
    "LBP": ("libra libanesa", "libras libanesas"),
    "LKR": ("rupia de Sri Lanka", "rupias de Sri Lanka"),
    "LRD": ("dólar liberiano", "dólares liberianos"),
    "LSL": ("loti lesotense", "malotis lesotenses"),
    "LYD": ("dinar libio", "dinares libios"),
    "MAD": ("dírham marroquí", "dírhams marroquíes"),
    "MDL": ("leu moldavo", "lei moldavos"),
    "MGA": ("ariary malgache", "ariarys malgaches"),
    "MKD": ("denar macedonio", "denares macedonios"),
    "MMK": ("kyat birmano", "kyats birmanos"),
    "MNT": ("tugrik mongol", "tugriks mongoles"),
    "MOP": ("pataca de Macao", "patacas de Macao"),
    "MRU": ("uguiya mauritana", "uguiyas mauritanas"),
    "MUR": ("rupia mauriciana", "rupias mauricianas"),
    "MVR": ("rufiyaa maldiva", "rufiyaas maldivas"),
    "MWK": ("kwacha malauí", "kwachas malauíes"),
    "MXN": ("peso mexicano", "pesos mexicanos"),
    "MYR": ("ringgit malayo", "ringgits malayos"),
    "MZN": ("metical mozambiqueño", "meticales mozambiqueños"),
    "NAD": ("dólar namibio", "dólares namibios"),
    "NGN": ("naira nigeriano", "nairas nigerianos"),
    "NIO": ("córdoba", "córdobas"),
    "NOK": ("corona noruega", "coronas noruegas"),
    "NPR": ("rupia nepalí", "rupias nepalíes"),
    "NZD": ("dólar neozelandés", "dólares neozelandeses"),
    "OMR": ("rial omaní", "riales omaníes"),
    "PEN": ("sol peruano", "soles peruanos"),
    "PGK": ("kina de Papúa Nueva Guinea", "kinas de Papúa Nueva Guinea"),
    "PHP": ("peso filipino", "pesos filipinos"),
    "PKR": ("rupia pakistaní", "rupias pakistaníes"),
    "PLN": ("esloti polaco", "eslotis polacos"),
    "PYG": ("guaraní", "guaraníes"),
    "QAR": ("rial catarí", "riales cataríes"),
    "RON": ("leu rumano", "lei rumanos"),
    "RSD": ("dinar serbio", "dinares serbios"),
    "RUB": ("rublo ruso", "rublos rusos"),
    "RWF": ("franco ruandés", "francos ruandeses"),
    "SAR": ("rial saudí", "riales saudíes"),
    "SBD": ("dólar de las Islas Salomón", "dólares de las Islas Salomón"),
    "SCR": ("rupia seychelense", "rupias seychelenses"),
    "SDG": ("libra sudanesa", "libras sudanesas"),
    "SEK": ("corona sueca", "coronas suecas"),
    "SGD": ("dólar de Singapur", "dólares de Singapur"),
    "SLE": ("leone sierraleonés", "leones sierraleoneses"),
    "SOS": ("chelín somalí", "chelines somalíes"),
    "SRD": ("dólar surinamés", "dólares surinameses"),
    "SSP": ("libra sursudanesa", "libras sursudanesas"),
    "STN": ("dobra santotomense", "dobras santotomenses"),
    "SYP": ("libra siria", "libras sirias"),
    "SZL": ("lilangeni suazi", "emalangeni suazis"),
    "THB": ("baht tailandés", "bahts tailandeses"),
    "TJS": ("somoni tayiko", "somonis tayikos"),
    "TMT": ("manat turcomano", "manats turcomanos"),
    "TND": ("dinar tunecino", "dinares tunecinos"),
    "TOP": ("paanga tongano", "paangas tonganos"),
    "TRY": ("lira turca", "liras turcas"),
    "TTD": ("dólar de Trinidad y Tobago", "dólares de Trinidad y Tobago"),
    "TWD": ("dólar taiwanés", "dólares taiwaneses"),
    "TZS": ("chelín tanzano", "chelines tanzanos"),
    "UAH": ("grivna ucraniana", "grivnas ucranianas"),
    "UGX": ("chelín ugandés", "chelines ugandeses"),
    "USD": ("dólar estadounidense", "dólares estadounidenses"),
    "UYU": ("peso uruguayo", "pesos uruguayos"),
    "UZS": ("som uzbeko", "soms uzbekos"),
    "VES": ("bolívar venezolano", "bolívares venezolanos"),
    "VND": ("dong vietnamita", "dongs vietnamitas"),
    "VUV": ("vatu vanuatuense", "vatus vanuatuenses"),
    "WST": ("tala samoano", "talas samoanos"),
    "XAF": ("franco CFA de África Central", "francos CFA de África Central"),
    "XCD": ("dólar del Caribe Oriental", "dólares del Caribe Oriental"),
    "XCG": ("florín del Caribe", "florines del Caribe"),
    "XOF": ("franco CFA de África Occidental", "francos CFA de África Occidental"),
    "XPF": ("franco CFP", "francos CFP"),
    "YER": ("rial yemení", "riales yemeníes"),
    "ZAR": ("rand sudafricano", "rands sudafricanos"),
    "ZMW": ("kwacha zambiano", "kwachas zambianos"),
}


def _sin_tildes(texto: str) -> str:
    return unicodedata.normalize("NFKD", texto).encode("ascii", "ignore").decode().lower()


# Opciones del formulario, en orden alfabético (sin que las tildes lo alteren): «Peso colombiano (COP)»
OPCIONES = sorted(
    ((codigo, f"{singular[0].upper()}{singular[1:]} ({codigo})") for codigo, (singular, _) in MONEDAS.items()),
    key=lambda opcion: _sin_tildes(opcion[1]),
)

# Moneda que se usa en cada país del catálogo (código ISO 3166-1 → ISO 4217).
# Chile no aparece: sus gastos ya van en pesos chilenos. Donde circulan dos
# monedas (Panamá, Zimbabue, Timor Oriental…) va la que usa el viajero.
MONEDA_DE_PAIS = {
    # África
    "DZ": "DZD", "AO": "AOA", "BJ": "XOF", "BW": "BWP", "BF": "XOF", "BI": "BIF", "CV": "CVE",
    "CM": "XAF", "CF": "XAF", "TD": "XAF", "KM": "KMF", "CG": "XAF", "CD": "CDF", "CI": "XOF",
    "DJ": "DJF", "EG": "EGP", "GQ": "XAF", "ER": "ERN", "SZ": "SZL", "ET": "ETB", "GA": "XAF",
    "GM": "GMD", "GH": "GHS", "GN": "GNF", "GW": "XOF", "KE": "KES", "LS": "LSL", "LR": "LRD",
    "LY": "LYD", "MG": "MGA", "MW": "MWK", "ML": "XOF", "MR": "MRU", "MU": "MUR", "MA": "MAD",
    "MZ": "MZN", "NA": "NAD", "NE": "XOF", "NG": "NGN", "RW": "RWF", "ST": "STN", "SN": "XOF",
    "SC": "SCR", "SL": "SLE", "SO": "SOS", "ZA": "ZAR", "SS": "SSP", "SD": "SDG", "TZ": "TZS",
    "TG": "XOF", "TN": "TND", "UG": "UGX", "ZM": "ZMW", "ZW": "USD",
    # América
    "CA": "CAD", "US": "USD", "MX": "MXN", "GL": "DKK", "BZ": "BZD", "CR": "CRC", "SV": "USD",
    "GT": "GTQ", "HN": "HNL", "NI": "NIO", "PA": "USD", "AG": "XCD", "BS": "BSD", "BB": "BBD",
    "CU": "CUP", "DM": "XCD", "DO": "DOP", "GD": "XCD", "HT": "HTG", "JM": "JMD", "KN": "XCD",
    "LC": "XCD", "VC": "XCD", "TT": "TTD", "PR": "USD", "AW": "AWG", "CW": "XCG", "AR": "ARS",
    "BO": "BOB", "BR": "BRL", "CO": "COP", "EC": "USD", "GY": "GYD", "PY": "PYG", "PE": "PEN",
    "SR": "SRD", "UY": "UYU", "VE": "VES",
    # Asia
    "AF": "AFN", "SA": "SAR", "AM": "AMD", "AZ": "AZN", "BH": "BHD", "BD": "BDT", "BT": "BTN",
    "BN": "BND", "KH": "KHR", "QA": "QAR", "CN": "CNY", "KP": "KPW", "KR": "KRW", "AE": "AED",
    "PH": "PHP", "GE": "GEL", "IN": "INR", "ID": "IDR", "IQ": "IQD", "IR": "IRR", "IL": "ILS",
    "JP": "JPY", "JO": "JOD", "KZ": "KZT", "KG": "KGS", "KW": "KWD", "LA": "LAK", "LB": "LBP",
    "MY": "MYR", "MV": "MVR", "MN": "MNT", "MM": "MMK", "NP": "NPR", "OM": "OMR", "PK": "PKR",
    "SG": "SGD", "SY": "SYP", "LK": "LKR", "TJ": "TJS", "TH": "THB", "TL": "USD", "TM": "TMT",
    "TR": "TRY", "UZ": "UZS", "VN": "VND", "YE": "YER", "TW": "TWD", "HK": "HKD", "MO": "MOP",
    "PS": "ILS",
    # Europa
    "AL": "ALL", "DE": "EUR", "AD": "EUR", "AT": "EUR", "BE": "EUR", "BY": "BYN", "BA": "BAM",
    "BG": "EUR", "CY": "EUR", "HR": "EUR", "DK": "DKK", "SK": "EUR", "SI": "EUR", "ES": "EUR",
    "EE": "EUR", "FI": "EUR", "FR": "EUR", "GR": "EUR", "HU": "HUF", "IE": "EUR", "IS": "ISK",
    "IT": "EUR", "LV": "EUR", "LI": "CHF", "LT": "EUR", "LU": "EUR", "MK": "MKD", "MT": "EUR",
    "MD": "MDL", "MC": "EUR", "ME": "EUR", "NO": "NOK", "NL": "EUR", "PL": "PLN", "PT": "EUR",
    "GB": "GBP", "CZ": "CZK", "RO": "RON", "RU": "RUB", "SM": "EUR", "RS": "RSD", "SE": "SEK",
    "CH": "CHF", "UA": "UAH", "VA": "EUR",
    # Oceanía
    "AU": "AUD", "FJ": "FJD", "MH": "USD", "SB": "SBD", "KI": "AUD", "FM": "USD", "NR": "AUD",
    "NZ": "NZD", "PW": "USD", "PG": "PGK", "WS": "WST", "TO": "TOP", "TV": "AUD", "VU": "VUV",
    "PF": "XPF",
}


def nombre_moneda(codigo: str, cantidad=2) -> str:
    """«peso colombiano» si la cantidad es 1; si no, «pesos colombianos»."""
    singular, plural = MONEDAS[codigo]
    return singular if cantidad == 1 else plural
