# Generated by Django 4.2.30 on 2026-09-02 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Viaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        help_text='Ciudad o región, ej: "París", "Bali", "Cartagena".',
                        max_length=100,
                        verbose_name="Destino",
                    ),
                ),
                ("pais", models.CharField(max_length=100, verbose_name="País")),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjalo vacío si el viaje todavía no termina o es un plan a futuro.",
                        null=True,
                        verbose_name="Fecha de término",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("completado", "Completado"),
                            ("en_progreso", "En progreso"),
                            ("planificado", "Planificado"),
                        ],
                        default="planificado",
                        editable=False,
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Detalles, recuerdos o lo que quieras anotar sobre este viaje.",
                        verbose_name="Notas del viaje",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viaje",
                "verbose_name_plural": "Viajes",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puede_crear_viajes",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, el usuario puede subir nuevos viajes y editar los suyos.",
                        verbose_name="Puede crear y editar viajes",
                    ),
                ),
                (
                    "puede_ver_otros",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, el usuario puede ver el diario de viajes de todos (solo lectura).",
                        verbose_name="Puede ver viajes de otros usuarios",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuario",
                "verbose_name_plural": "Perfiles de usuario",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Mg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mg_dados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mg",
                        to="viajes.viaje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mg",
                "verbose_name_plural": "Mg",
                "ordering": ["-creado"],
                "unique_together": {("viaje", "usuario")},
            },
        ),
    ]
