# Generated by Django 4.2.30 on 2026-09-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("viajes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoViaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to="viajes/%Y/%m/", verbose_name="Foto"),
                ),
                ("subida", models.DateTimeField(auto_now_add=True)),
                (
                    "viaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="viajes.viaje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de viaje",
                "verbose_name_plural": "Fotos de viaje",
                "ordering": ["subida"],
            },
        ),
    ]
